# Generated by Django 3.0.8 on 2020-07-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavMtId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название из МТ', max_length=250, null=True, verbose_name='name')),
                ('nav_id', models.IntegerField(help_text='Идентификатор навигации', verbose_name='nav_id')),
                ('mt_id', models.IntegerField(blank=True, help_text='Идентификатор МТ', null=True, verbose_name='mt_id')),
            ],
            options={
                'verbose_name': 'площадка МТ',
                'verbose_name_plural': 'площадки МТ',
            },
        ),
    ]
