name: deploy to prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: nav-prod
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: cp /nav_info/_config/.env ./.env
      - name: Fix docker-compose
        run: | 
          rm -f ./docker-compose.yml
          cp /nav_info/_config/docker-compose.yml ./docker-compose.yml
      - name: Create volumes
        run: |
          docker volume create nav_db_data
      - name: Make up
        run: make up
        
